#
#
# This file was autogenerated by PythonOnWheels (copow version)
# But YOU CAN EDIT THIS FILE SAFELY
# It will not be overwritten by python_on_wheels
# unless you force it with the -f or --force option
# 
# 2014/06/05 14:28:25


import sys
import os

import atest.lib.powlib
from atest.lib.pow_objects import Migration
from atest.models.copow_log import Copow_log

migration = Migration()

def up():
    """ up method will be executed when running do_migrate -d up"""
    copow_log = Copow_log( schema  = {
           "time"       :      { "type" : "date" },   
           "logstr"     :      { "type" : "Text" },
           "user  "     :      { "type" : "Text" }
           #"a_more_complex_one"    :       { "type" : "Text" , "index" : True, "default" : "something"}
      } 
    )

    # creates the tabke (collection) and the schema in migrations/schemas/
    # creates a collection named log with a maximum size of 5 megabytes and a maximum of 5000 documents.
    # See: http://docs.mongodb.org/manual/reference/method/db.createCollection/
    migration.create_table(copow_log, capped=True, size=5242880, max=5000  )
    
    print("  Successfully migrated copow_log -> mehtod: up()")
    
def down():
    """ down method will be executed when running do_migrate -d down"""
    # drops the table (collection) and removes the schema from migrations/schemas/
    copow_log = Copow_log()
    migration.drop_table(copow_log)
    print("  Successfully migrated copow_log -> mehtod: down()")
    
