#
#
# This file was autogenerated by PythonOnWheels (copow version)
# But YOU CAN EDIT THIS FILE SAFELY
# It will not be overwritten by python_on_wheels
# unless you force it with the -f or --force option
# 
# #DATE


import sys
import os

import copow.lib.powlib
import copow.lib.migration
from copow.lib.migration import Column
from #APPNAME.models.#MODEL1 import #UPMODEL1 
from #APPNAME.models.#MODEL2 import #UPMODEL2

def up(self):
    """ up method will be executed when running do_migrate -d up"""
    
    # below you can see an example of a typical relation migratio.
    # besides has_many, also : has_one and is_tree are supproted.

    #MODEL1 = #UPMODEL1()
    #MODEL2 = #UPMODEL2()
    
    #MODEL1.has_many(#MODEL2)
    
    
def down(self):
    """ down method will be executed when running do_migrate -d down"""
    # removes the relation between the models.
    #MODEL1 = #UPMODEL1()
    #MODEL2 = #UPMODEL2()
    
    #MODEL1.remove_relation(#MODEL2)